---
- hosts: tag_ansible_group_default_consul_demo
  connection: local
  gather_facts: False
  tasks:
  - name: Print hostname
    debug:
      msg: "{{ public_ip_address }}"
  - name: Print hostname
    debug:
      msg: "{{ lookup('aws_ssm', '/infrastructure/credentials/bigip/' + public_ip_address ) }}"
  - name: Ensure AS3 is running and available
    uri:
      url: "https://{{ public_ip_address }}/mgmt/shared/appsvcs/info"
      user: "admin"
      password: "{{ lookup('aws_ssm', '/infrastructure/credentials/bigip/' + public_ip_address ) }}"
      method: GET
      force_basic_auth: true
      status_code: 200
      validate_certs: false
    register: result
    until: result.status == 200
    retries: 240 # 720 * 5 seconds = 1hour (60*60/5)
    delay: 5 # Every 5 seconds
  - name: Apply AS3 Declaration
    uri:
      url: "https://{{ public_ip_address }}/mgmt/shared/appsvcs/declare"
      user: "admin"
      password: "{{ lookup('aws_ssm', '/infrastructure/credentials/bigip/' + public_ip_address ) }}"
      method: POST
      body_format: "json"
      body: "{{ lookup('template','templates/as3.j2') }}"
      force_basic_auth: true
      status_code: 200, 201
      timeout: 30
      validate_certs: false
